version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXConferenceProject
  gitServerName: chko_git
  gitUrl: https://github.com/chkoprivate/TechXConferenceProject
  gitUsername: chkoprivate
  gitBranch: main
- name: CustomerData
  version: "1.0"
  gitServerName: Git_Christian-Kopecki
  gitUrl: https://github.ibm.com/Christian-Kopecki
  gitUsername: Christian-Kopecki
  gitBranch: main
services:
- serviceName: project.techxconference.integrations:shipOrder
  packages:
  - name: TechXConferenceProject
    version: "1.0"
  - name: CustomerData
    version: "1.0"
- serviceName: CustomerData.impl:getCustomerbyID
  packages:
  - name: CustomerData
    version: "1.0"
- serviceName: pub.cache:get
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
