version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXConferenceProject
  gitServerName: chko_git
  gitUrl: https://github.com/chkoprivate/TechXConferenceProject
  gitUsername: chkoprivate
  gitBranch: main
- name: CustomerData
  version: "1.0"
  gitServerName: Git_Christian-Kopecki
  gitUrl: https://github.ibm.com/Christian-Kopecki
  gitUsername: Christian-Kopecki
  gitBranch: main
services:
- serviceName: project.techxconference.integrations:getCustomerbyID
  packages:
  - name: TechXConferenceProject
    version: "1.0"
  - name: OrderShipment
    version: "1.0"
  - name: CustomerData
    version: "1.0"
- serviceName: OrderShipment.impl:getCustomerbyID
  packages:
  - name: OrderShipment
    version: "1.0"
- serviceName: pub.cache:get
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: CustomerData.impl:getCustomerbyID
  packages:
  - name: CustomerData
    version: "1.0"
- serviceName: CustomerData.utils.cache:getCacheData
  packages:
  - name: CustomerData
    version: "1.0"
- serviceName: pub.cache:getKeys
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.cache:getAll
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.document:sortDocuments
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.techxconference.integrations:ShippingOrder
  packages:
  - name: TechXConferenceProject
    version: "1.0"
  - name: CustomerData
    version: "1.0"
- serviceName: project.techxconference.integrations:shipOrder
  packages:
  - name: TechXConferenceProject
    version: "1.0"
  - name: CustomerData
    version: "1.0"
