version: "1.0"
info:
  model: int-scaffold
packages:
- name: TechXConferenceProject
  gitServerName: chko_git
  gitUrl: https://github.com/chkoprivate/TechXConferenceProject
  gitUsername: chkoprivate
  gitBranch: main
